[target.x86_64-unknown-linux-musl]
linker = "rust-lld"

[build]
rustflags = [
    "--deny", "warnings",
    "-C", "opt-level=3",
    "-C", "target-cpu=native",
]

[profile.dev]
rustflags = ["-Dwarnings", "-Dclippy::all"]

[profile.release]
rustflags = ["-Dwarnings", "-Dclippy::all"]
lto = "fat"