name: Quantum Forge CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - "*"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install CUDA Toolkit
        uses: Jimver/cuda-toolkit@v0.2.21
        with:
          method: "network"
          linux-local-args: "toolkit"

      - name: Build Quantum Forge
        run: cargo build --release

      - name: Run Tests
        run: cargo test --verbose
