name: Qitara CI
on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - "*"
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libsoup-3.0-dev libjavascriptcoregtk-4.1-dev webkit2gtk-4.1
      - name: Run Tests
        run: cargo test --verbose
      - name: Run Linter
        run: cargo clippy
